name: QIO

on:
  push:
    branches:
      - qio
    paths:
      - 'boards/**'
      - 'extend/**'
      - 'examples/**'
      - '**.json'
      - '**.py'

jobs:
  CodeCheck:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v2
      with:
        submodules: "recursive"

    - name: cppcheck
      uses: Qful/check-action@master
      with:
        github_token: ${{ secrets.OSQ_REPO_TOKEN }}
        enable: all
        inconclusive: disable
        inline_suppression: disable
        force_language: c
        force: enable
        max_ctu_depth: 2
        std: c11
        output_file: ./codecheck.txt
        other_options: --bug-hunting --verbose --std=c11

    - name: report
      uses: Qful/check-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.OSQ_REPO_TOKEN }}
        BRANCH_NAME: 'master'

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: code_check_report
        path: codecheck.txt

  PIO:
    strategy:
      fail-fast: false
      matrix:
        example:
          - "twr-button"
          - "twr-climate-module"
          - "twr-ds18b20-multiple"
          - "twr-ds18b20-single"
          - "twr-gps-module"
          - "twr-infrared-receiver"
          - "twr-lcd-text"
          - "twr-led-on-off"
          - "twr-led-strip"
          - "twr-log"
          - "twr-lux-meter-tag"
          - "twr-nfc-tag"
          - "twr-onewire-i2c"
          - "twr-onewire-relay"
          - "twr-onewire-search"
          - "twr-pir-module"
          - "twr-radio-base"
          - "twr-radio-remote"
          - "twr-scheduler-advanced"
          - "twr-scheduler-basics"
          - "twr-sigfox"
          - "twr-skeleton"
          - "twr-switch"
          - "twr-ultrasound"
          - "twr-usb-sensors"

        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/OS-Q/M03/releases/latest/download/qio.zip
          pio platform install https://github.com/OS-Q/P42/archive/qio.zip

      - name: Build examples
        working-directory: examples
        run: |
          pio run -d ${{ matrix.example }}


